#!/bin/bash

HEADER(){
printf "\e[96m                                           
 _____ _____ _____ __    _____ _____ __ __ 
|  _  |  |  |  _  |  |  |  _  |   | |  |  |
|   __|     |     |  |__|     | | | |-   -|v1.3.3
|__|  |__|__|__|__|_____|__|__|_|___|__|__|installation!\e[0m\n\n"
}

HEADER

USAGE(){
printf "Usage: $(basename $0) [OPTION]\n\nOptions:\n\n	-0 \e[91m[token]\e[0m	Slack Configuration \e[91m[!]\e[0m\n	-1 \e[91m[token]\e[0m	PHALANX-API Configuration \e[91m[!]\e[0m\n	-2		Tools Installation\n 	-3		PHALANX Installation\n\n"
}

PATHTOSCRIPTS="$PWD/phalanx-tools"

if [[ -z "${1}" ]] 
then
	USAGE
elif [[ "${1}" = "-0" ]]
then
	if [[ -z "${2}" ]]
	then
		printf "\e[31m$(basename $0): error: please provide slack token\e[0m\n" >&2
		exit 1
	else
		echo "${2}" 1> $PATHTOSCRIPTS/slack.token
		printf "\e[32m[*] Slack has been configured\e[0m\n"
	fi
elif [[ "${1}" = "-1" ]]
then
	if [[ -z "${2}" ]]
	then
		printf "\e[31m$(basename $0): error: please provide phalanx token\e[0m\n" >&2
		exit 1
	else
		echo "${2}" 1> $PATHTOSCRIPTS/phalanx.token
		printf "\e[32m[*] Phalanx has been configured\e[0m\n"
	fi
elif [[ "${1}" = "-2" ]]
then
	printf "\e[93m[-] Dependencies Installation Start\e[0m\n"
	sudo apt-get install -y snapd
	echo -ne '\e[92m########                   (33%)\e[0m\r'
	sleep 1
	sudo apt-get install -y amass
	echo -ne '\e[92m################           (66%)\e[0m\r'
	sleep 1
	sudo docker pull ice3man/subfinder
	echo -ne '\e[92m########################## (100%)\e[0m\r'
	echo -ne '\n'
	printf "\e[32m[+] Dependencies Installation End\e[0m\n"
elif [[ "${1}" = "-3" ]]
then
	if [[ ! -f "$PATHTOSCRIPTS/slack.token" ]]
	then
		printf "\e[31m$(basename $0): error: slack token is required\e[0m\n" >&2
		exit 1
	fi
	if [[ ! -f "$PATHTOSCRIPTS/phalanx.token" ]]
	then
		printf "\e[31m$(basename $0): error: phalanx token is required\e[0m\n" >&2
		exit 1
	fi
	printf "\e[93m[-] PHALANX Installation Start\e[0m\n"
	chmod 777 phalanx-tools
	echo -ne '\e[92m########                   (33%)\e[0m\r'
	sleep 1
	chmod 777 phalanx
	echo -ne '\e[92m################           (66%)\e[0m\r'
	sleep 1
	cp -R phalanx /usr/local/bin
	cp -R phalanx-tools /usr/local/bin/phalanx-tools
	echo -ne '\e[92m########################## (100%)\e[0m\r'
	echo -ne '\n'
	printf "\e[32m[+] PHALANX Installation End\e[0m\n"
else
	printf "\e[31m$(basename $0): error: unknown option: \"${1}\"\e[0m\n" >&2
	exit 1
fi
